/* Generated By:JavaCC: Do not edit this line. StandardTokenizerConstants.java */
package srl.corpus.token;

public interface StandardTokenizerConstants {

  int EOF = 0;
  int ALPHANUM = 1;
  int BEGIN_TAG = 2;
  int END_TAG = 3;
  int APOSTROPHE = 4;
  int ACRONYM = 5;
  int COMPANY = 6;
  int EMAIL = 7;
  int HOST = 8;
  int NUM = 9;
  int PUNCTUATION = 10;
  int P = 11;
  int HAS_DIGIT = 12;
  int ALPHA = 13;
  int LETTER = 14;
  int PUNC = 15;
  int CJ = 16;
  int KOREAN = 17;
  int DIGIT = 18;
  int NOISE = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<BEGIN_TAG>",
    "<END_TAG>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<PUNCTUATION>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<PUNC>",
    "<CJ>",
    "<KOREAN>",
    "<DIGIT>",
    "<NOISE>",
  };

}
