/* Generated By:JavaCC: Do not edit this line. StandardTokenizerConstants.java */
/* 
 * Copyright (c) 2008, National Institute of Informatics
 *
 * This file is part of SRL, and is free
 * software, licenced under the GNU Library General Public License,
 * Version 2, June 1991.
 *
 * A copy of this licence is included in the distribution in the file
 * licence.html, and is also available at http://www.fsf.org/licensing/licenses/info/GPLv2.html.
*/
package srl.corpus.token;

public interface StandardTokenizerConstants {

  int EOF = 0;
  int ALPHANUM = 1;
  int BEGIN_TAG = 2;
  int END_TAG = 3;
  int APOSTROPHE = 4;
  int ACRONYM = 5;
  int COMPANY = 6;
  int EMAIL = 7;
  int HOST = 8;
  int NUM = 9;
  int PUNCTUATION = 10;
  int P = 11;
  int HAS_DIGIT = 12;
  int ALPHA = 13;
  int LETTER = 14;
  int PUNC = 15;
  int CJ = 16;
  int SPACE = 17;
  int KOREAN = 18;
  int DIGIT = 19;
  int NOISE = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<BEGIN_TAG>",
    "<END_TAG>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<PUNCTUATION>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<PUNC>",
    "<CJ>",
    "<SPACE>",
    "<KOREAN>",
    "<DIGIT>",
    "<NOISE>",
  };

}
