/* Generated By:JavaCC: Do not edit this line. SrlParserConstants.java */
/* 
 * Copyright (c) 2008, National Institute of Informatics
 *
 * This file is part of SRL, and is free
 * software, licenced under the GNU Library General Public License,
 * Version 2, June 1991.
 *
 * A copy of this licence is included in the distribution in the file
 * licence.html, and is also available at http://www.fsf.org/licensing/licenses/info/GPLv2.html.
 */
package srl.rule.parser;

public interface SrlParserConstants {

  int EOF = 0;
  int EOL = 3;
  int STRMATCH = 4;
  int STRMATCH_APPROX = 5;
  int STRMATCH_REGEX = 6;
  int STRMATCH_ORTH = 7;
  int BEGINS = 8;
  int ENDS = 9;
  int CONTAINS = 10;
  int WORDS = 11;
  int OPEN_PARA = 12;
  int CLOSE_PARA = 13;
  int OPEN_BRACE = 14;
  int CLOSE_BRACE = 15;
  int COMMA = 16;
  int PERCENT = 17;
  int IMPLIES = 18;
  int COLON = 19;
  int SEMICOLON = 20;
  int STRING_LITERAL = 21;
  int WORDLIST = 22;
  int VAR = 23;
  int NUMBER = 24;
  int WORD = 25;
  int COMMENT = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\" \"",
    "<EOL>",
    "\"strmatches\"",
    "\"approx\"",
    "\"regex\"",
    "\"ortho\"",
    "\"begins\"",
    "\"ends\"",
    "\"contains\"",
    "\"words\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"%\"",
    "\":-\"",
    "\":\"",
    "\";\"",
    "<STRING_LITERAL>",
    "<WORDLIST>",
    "<VAR>",
    "<NUMBER>",
    "<WORD>",
    "<COMMENT>",
  };

}
