/* Generated By:JavaCC: Do not edit this line. PreTokenizerConstants.java */
/* 
 * Copyright (c) 2008, National Institute of Informatics
 *
 * This file is part of SRL, and is free
 * software, licenced under the GNU Library General Public License,
 * Version 2, June 1991.
 *
 * A copy of this licence is included in the distribution in the file
 * licence.html, and is also available at http://www.fsf.org/licensing/licenses/info/GPLv2.html.
*/
package srl.corpus.pre;

public interface PreTokenizerConstants {

  int EOF = 0;
  int BEGIN_TAG = 1;
  int END_TAG = 2;
  int SPACE = 3;
  int SPLITTER = 4;
  int ANYTHING = 5;
  int ALPHANUM = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<BEGIN_TAG>",
    "<END_TAG>",
    "\" \"",
    "\"\\u00b6\"",
    "<ANYTHING>",
    "<ALPHANUM>",
  };

}
